import Head from "next/head";
import App from "@/App";
import Footer from "@/components/organisms/Footer";
import footerData from "@/data/FooterData";

export default function Index() {
  return (
    <>
      <Head>
        <title>Creativedog (Prueba Técnica)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/favicon.ico" />
      </Head>
      <div>
        <App/>
        <Footer
          logo={footerData.logo}
          socialIcons={footerData.social}
          terms={footerData.terms}
          copyright={footerData.copyright}
          designAndDev={footerData.designAndDev}
        />
      </div>
    </>
  );
}